#!/usr/bin/env python
# -*- coding: UTF-8 -*-
'''
@Project ：ultralytics 
@File    ：model_info.py
@Author  ：DELL(zhuangxujun)
@Date    ：2025/11/5 15:56 
@explain : 
'''

from ultralytics import YOLO, RTDETR

# Ultralytics 的 YOLO 模型加载预训练权重（.pt 文件）后，默认处于 推理 / 评估模式（eval mode）
# model = YOLO("yolov8s.pt")  # YOLOv8s summary: 129 layers, 11,166,560 parameters, 0 gradients, 28.8 GFLOPs
# model = YOLO("yolov8s.yaml")  # YOLOv8s summary: 129 layers, 11,166,560 parameters, 11,166,544 gradients, 28.8 GFLOPs
model = YOLO("yolov8n.yaml")  #
# model = YOLO("yolov8l.yaml")  # YOLOv8l summary: 209 layers, 43,691,520 parameters, 43,691,504 gradients, 165.7 GFLOPs


# model = RTDETR("yolov8s-rtdetr.yaml")  # YOLOv8s-rtdetr summary: 235 layers, 16,518,572 parameters, 16,518,572 gradients, 32.8 GFLOPs
# model = RTDETR("yolov8s-rtdetr.pt")  # error

# model = YOLO("yolov8s-rtdetr.yaml")  #
# model = YOLO("yolov8s-rtdetr.pt")  #

# model = RTDETR("rtdetr-l.pt")  # rt-detr-l summary: 449 layers, 32,970,476 parameters, 0 gradients, 108.3 GFLOPs

# model = RTDETR("rtdetr-resnet50.yaml")  # rtdetr-resnet50 summary: 402 layers, 42,925,132 parameters, 42,925,132 gradients, 130.8 GFLOPs
# # 打印模型的所有参数键名
# print("模型的键名:")
# for name, _ in model.model.named_parameters():
#     print(name)

#
model.info()


"""
RT-DETR 模型的键名:
model.0.layer.0.conv.weight
model.0.layer.0.bn.weight
model.0.layer.0.bn.bias
model.1.layer.0.cv1.conv.weight
model.1.layer.0.cv1.bn.weight
model.1.layer.0.cv1.bn.bias
model.1.layer.0.cv2.conv.weight
model.1.layer.0.cv2.bn.weight
model.1.layer.0.cv2.bn.bias
model.1.layer.0.cv3.conv.weight
model.1.layer.0.cv3.bn.weight
model.1.layer.0.cv3.bn.bias
model.1.layer.0.shortcut.0.conv.weight
model.1.layer.0.shortcut.0.bn.weight
model.1.layer.0.shortcut.0.bn.bias
model.1.layer.1.cv1.conv.weight
model.1.layer.1.cv1.bn.weight
model.1.layer.1.cv1.bn.bias
model.1.layer.1.cv2.conv.weight
model.1.layer.1.cv2.bn.weight
model.1.layer.1.cv2.bn.bias
model.1.layer.1.cv3.conv.weight
model.1.layer.1.cv3.bn.weight
model.1.layer.1.cv3.bn.bias
model.1.layer.2.cv1.conv.weight
model.1.layer.2.cv1.bn.weight
model.1.layer.2.cv1.bn.bias
model.1.layer.2.cv2.conv.weight
model.1.layer.2.cv2.bn.weight
model.1.layer.2.cv2.bn.bias
model.1.layer.2.cv3.conv.weight
model.1.layer.2.cv3.bn.weight
model.1.layer.2.cv3.bn.bias
model.2.layer.0.cv1.conv.weight
model.2.layer.0.cv1.bn.weight
model.2.layer.0.cv1.bn.bias
model.2.layer.0.cv2.conv.weight
model.2.layer.0.cv2.bn.weight
model.2.layer.0.cv2.bn.bias
model.2.layer.0.cv3.conv.weight
model.2.layer.0.cv3.bn.weight
model.2.layer.0.cv3.bn.bias
model.2.layer.0.shortcut.0.conv.weight
model.2.layer.0.shortcut.0.bn.weight
model.2.layer.0.shortcut.0.bn.bias
model.2.layer.1.cv1.conv.weight
model.2.layer.1.cv1.bn.weight
model.2.layer.1.cv1.bn.bias
model.2.layer.1.cv2.conv.weight
model.2.layer.1.cv2.bn.weight
model.2.layer.1.cv2.bn.bias
model.2.layer.1.cv3.conv.weight
model.2.layer.1.cv3.bn.weight
model.2.layer.1.cv3.bn.bias
model.2.layer.2.cv1.conv.weight
model.2.layer.2.cv1.bn.weight
model.2.layer.2.cv1.bn.bias
model.2.layer.2.cv2.conv.weight
model.2.layer.2.cv2.bn.weight
model.2.layer.2.cv2.bn.bias
model.2.layer.2.cv3.conv.weight
model.2.layer.2.cv3.bn.weight
model.2.layer.2.cv3.bn.bias
model.2.layer.3.cv1.conv.weight
model.2.layer.3.cv1.bn.weight
model.2.layer.3.cv1.bn.bias
model.2.layer.3.cv2.conv.weight
model.2.layer.3.cv2.bn.weight
model.2.layer.3.cv2.bn.bias
model.2.layer.3.cv3.conv.weight
model.2.layer.3.cv3.bn.weight
model.2.layer.3.cv3.bn.bias
model.3.layer.0.cv1.conv.weight
model.3.layer.0.cv1.bn.weight
model.3.layer.0.cv1.bn.bias
model.3.layer.0.cv2.conv.weight
model.3.layer.0.cv2.bn.weight
model.3.layer.0.cv2.bn.bias
model.3.layer.0.cv3.conv.weight
model.3.layer.0.cv3.bn.weight
model.3.layer.0.cv3.bn.bias
model.3.layer.0.shortcut.0.conv.weight
model.3.layer.0.shortcut.0.bn.weight
model.3.layer.0.shortcut.0.bn.bias
model.3.layer.1.cv1.conv.weight
model.3.layer.1.cv1.bn.weight
model.3.layer.1.cv1.bn.bias
model.3.layer.1.cv2.conv.weight
model.3.layer.1.cv2.bn.weight
model.3.layer.1.cv2.bn.bias
model.3.layer.1.cv3.conv.weight
model.3.layer.1.cv3.bn.weight
model.3.layer.1.cv3.bn.bias
model.3.layer.2.cv1.conv.weight
model.3.layer.2.cv1.bn.weight
model.3.layer.2.cv1.bn.bias
model.3.layer.2.cv2.conv.weight
model.3.layer.2.cv2.bn.weight
model.3.layer.2.cv2.bn.bias
model.3.layer.2.cv3.conv.weight
model.3.layer.2.cv3.bn.weight
model.3.layer.2.cv3.bn.bias
model.3.layer.3.cv1.conv.weight
model.3.layer.3.cv1.bn.weight
model.3.layer.3.cv1.bn.bias
model.3.layer.3.cv2.conv.weight
model.3.layer.3.cv2.bn.weight
model.3.layer.3.cv2.bn.bias
model.3.layer.3.cv3.conv.weight
model.3.layer.3.cv3.bn.weight
model.3.layer.3.cv3.bn.bias
model.3.layer.4.cv1.conv.weight
model.3.layer.4.cv1.bn.weight
model.3.layer.4.cv1.bn.bias
model.3.layer.4.cv2.conv.weight
model.3.layer.4.cv2.bn.weight
model.3.layer.4.cv2.bn.bias
model.3.layer.4.cv3.conv.weight
model.3.layer.4.cv3.bn.weight
model.3.layer.4.cv3.bn.bias
model.3.layer.5.cv1.conv.weight
model.3.layer.5.cv1.bn.weight
model.3.layer.5.cv1.bn.bias
model.3.layer.5.cv2.conv.weight
model.3.layer.5.cv2.bn.weight
model.3.layer.5.cv2.bn.bias
model.3.layer.5.cv3.conv.weight
model.3.layer.5.cv3.bn.weight
model.3.layer.5.cv3.bn.bias
model.4.layer.0.cv1.conv.weight
model.4.layer.0.cv1.bn.weight
model.4.layer.0.cv1.bn.bias
model.4.layer.0.cv2.conv.weight
model.4.layer.0.cv2.bn.weight
model.4.layer.0.cv2.bn.bias
model.4.layer.0.cv3.conv.weight
model.4.layer.0.cv3.bn.weight
model.4.layer.0.cv3.bn.bias
model.4.layer.0.shortcut.0.conv.weight
model.4.layer.0.shortcut.0.bn.weight
model.4.layer.0.shortcut.0.bn.bias
model.4.layer.1.cv1.conv.weight
model.4.layer.1.cv1.bn.weight
model.4.layer.1.cv1.bn.bias
model.4.layer.1.cv2.conv.weight
model.4.layer.1.cv2.bn.weight
model.4.layer.1.cv2.bn.bias
model.4.layer.1.cv3.conv.weight
model.4.layer.1.cv3.bn.weight
model.4.layer.1.cv3.bn.bias
model.4.layer.2.cv1.conv.weight
model.4.layer.2.cv1.bn.weight
model.4.layer.2.cv1.bn.bias
model.4.layer.2.cv2.conv.weight
model.4.layer.2.cv2.bn.weight
model.4.layer.2.cv2.bn.bias
model.4.layer.2.cv3.conv.weight
model.4.layer.2.cv3.bn.weight
model.4.layer.2.cv3.bn.bias
model.5.conv.weight
model.5.bn.weight
model.5.bn.bias
model.6.ma.in_proj_weight
model.6.ma.in_proj_bias
model.6.ma.out_proj.weight
model.6.ma.out_proj.bias
model.6.fc1.weight
model.6.fc1.bias
model.6.fc2.weight
model.6.fc2.bias
model.6.norm1.weight
model.6.norm1.bias
model.6.norm2.weight
model.6.norm2.bias
model.7.conv.weight
model.7.bn.weight
model.7.bn.bias
model.9.conv.weight
model.9.bn.weight
model.9.bn.bias
model.11.cv1.conv.weight
model.11.cv1.bn.weight
model.11.cv1.bn.bias
model.11.cv2.conv.weight
model.11.cv2.bn.weight
model.11.cv2.bn.bias
model.11.m.0.conv1.conv.weight
model.11.m.0.conv1.bn.weight
model.11.m.0.conv1.bn.bias
model.11.m.0.conv2.conv.weight
model.11.m.0.conv2.bn.weight
model.11.m.0.conv2.bn.bias
model.11.m.1.conv1.conv.weight
model.11.m.1.conv1.bn.weight
model.11.m.1.conv1.bn.bias
model.11.m.1.conv2.conv.weight
model.11.m.1.conv2.bn.weight
model.11.m.1.conv2.bn.bias
model.11.m.2.conv1.conv.weight
model.11.m.2.conv1.bn.weight
model.11.m.2.conv1.bn.bias
model.11.m.2.conv2.conv.weight
model.11.m.2.conv2.bn.weight
model.11.m.2.conv2.bn.bias
model.12.conv.weight
model.12.bn.weight
model.12.bn.bias
model.14.conv.weight
model.14.bn.weight
model.14.bn.bias
model.16.cv1.conv.weight
model.16.cv1.bn.weight
model.16.cv1.bn.bias
model.16.cv2.conv.weight
model.16.cv2.bn.weight
model.16.cv2.bn.bias
model.16.m.0.conv1.conv.weight
model.16.m.0.conv1.bn.weight
model.16.m.0.conv1.bn.bias
model.16.m.0.conv2.conv.weight
model.16.m.0.conv2.bn.weight
model.16.m.0.conv2.bn.bias
model.16.m.1.conv1.conv.weight
model.16.m.1.conv1.bn.weight
model.16.m.1.conv1.bn.bias
model.16.m.1.conv2.conv.weight
model.16.m.1.conv2.bn.weight
model.16.m.1.conv2.bn.bias
model.16.m.2.conv1.conv.weight
model.16.m.2.conv1.bn.weight
model.16.m.2.conv1.bn.bias
model.16.m.2.conv2.conv.weight
model.16.m.2.conv2.bn.weight
model.16.m.2.conv2.bn.bias
model.17.conv.weight
model.17.bn.weight
model.17.bn.bias
model.19.cv1.conv.weight
model.19.cv1.bn.weight
model.19.cv1.bn.bias
model.19.cv2.conv.weight
model.19.cv2.bn.weight
model.19.cv2.bn.bias
model.19.m.0.conv1.conv.weight
model.19.m.0.conv1.bn.weight
model.19.m.0.conv1.bn.bias
model.19.m.0.conv2.conv.weight
model.19.m.0.conv2.bn.weight
model.19.m.0.conv2.bn.bias
model.19.m.1.conv1.conv.weight
model.19.m.1.conv1.bn.weight
model.19.m.1.conv1.bn.bias
model.19.m.1.conv2.conv.weight
model.19.m.1.conv2.bn.weight
model.19.m.1.conv2.bn.bias
model.19.m.2.conv1.conv.weight
model.19.m.2.conv1.bn.weight
model.19.m.2.conv1.bn.bias
model.19.m.2.conv2.conv.weight
model.19.m.2.conv2.bn.weight
model.19.m.2.conv2.bn.bias
model.20.conv.weight
model.20.bn.weight
model.20.bn.bias
model.22.cv1.conv.weight
model.22.cv1.bn.weight
model.22.cv1.bn.bias
model.22.cv2.conv.weight
model.22.cv2.bn.weight
model.22.cv2.bn.bias
model.22.m.0.conv1.conv.weight
model.22.m.0.conv1.bn.weight
model.22.m.0.conv1.bn.bias
model.22.m.0.conv2.conv.weight
model.22.m.0.conv2.bn.weight
model.22.m.0.conv2.bn.bias
model.22.m.1.conv1.conv.weight
model.22.m.1.conv1.bn.weight
model.22.m.1.conv1.bn.bias
model.22.m.1.conv2.conv.weight
model.22.m.1.conv2.bn.weight
model.22.m.1.conv2.bn.bias
model.22.m.2.conv1.conv.weight
model.22.m.2.conv1.bn.weight
model.22.m.2.conv1.bn.bias
model.22.m.2.conv2.conv.weight
model.22.m.2.conv2.bn.weight
model.22.m.2.conv2.bn.bias
model.23.input_proj.0.0.weight
model.23.input_proj.0.1.weight
model.23.input_proj.0.1.bias
model.23.input_proj.1.0.weight
model.23.input_proj.1.1.weight
model.23.input_proj.1.1.bias
model.23.input_proj.2.0.weight
model.23.input_proj.2.1.weight
model.23.input_proj.2.1.bias
model.23.decoder.layers.0.self_attn.in_proj_weight
model.23.decoder.layers.0.self_attn.in_proj_bias
model.23.decoder.layers.0.self_attn.out_proj.weight
model.23.decoder.layers.0.self_attn.out_proj.bias
model.23.decoder.layers.0.norm1.weight
model.23.decoder.layers.0.norm1.bias
model.23.decoder.layers.0.cross_attn.sampling_offsets.weight
model.23.decoder.layers.0.cross_attn.sampling_offsets.bias
model.23.decoder.layers.0.cross_attn.attention_weights.weight
model.23.decoder.layers.0.cross_attn.attention_weights.bias
model.23.decoder.layers.0.cross_attn.value_proj.weight
model.23.decoder.layers.0.cross_attn.value_proj.bias
model.23.decoder.layers.0.cross_attn.output_proj.weight
model.23.decoder.layers.0.cross_attn.output_proj.bias
model.23.decoder.layers.0.norm2.weight
model.23.decoder.layers.0.norm2.bias
model.23.decoder.layers.0.linear1.weight
model.23.decoder.layers.0.linear1.bias
model.23.decoder.layers.0.linear2.weight
model.23.decoder.layers.0.linear2.bias
model.23.decoder.layers.0.norm3.weight
model.23.decoder.layers.0.norm3.bias
model.23.decoder.layers.1.self_attn.in_proj_weight
model.23.decoder.layers.1.self_attn.in_proj_bias
model.23.decoder.layers.1.self_attn.out_proj.weight
model.23.decoder.layers.1.self_attn.out_proj.bias
model.23.decoder.layers.1.norm1.weight
model.23.decoder.layers.1.norm1.bias
model.23.decoder.layers.1.cross_attn.sampling_offsets.weight
model.23.decoder.layers.1.cross_attn.sampling_offsets.bias
model.23.decoder.layers.1.cross_attn.attention_weights.weight
model.23.decoder.layers.1.cross_attn.attention_weights.bias
model.23.decoder.layers.1.cross_attn.value_proj.weight
model.23.decoder.layers.1.cross_attn.value_proj.bias
model.23.decoder.layers.1.cross_attn.output_proj.weight
model.23.decoder.layers.1.cross_attn.output_proj.bias
model.23.decoder.layers.1.norm2.weight
model.23.decoder.layers.1.norm2.bias
model.23.decoder.layers.1.linear1.weight
model.23.decoder.layers.1.linear1.bias
model.23.decoder.layers.1.linear2.weight
model.23.decoder.layers.1.linear2.bias
model.23.decoder.layers.1.norm3.weight
model.23.decoder.layers.1.norm3.bias
model.23.decoder.layers.2.self_attn.in_proj_weight
model.23.decoder.layers.2.self_attn.in_proj_bias
model.23.decoder.layers.2.self_attn.out_proj.weight
model.23.decoder.layers.2.self_attn.out_proj.bias
model.23.decoder.layers.2.norm1.weight
model.23.decoder.layers.2.norm1.bias
model.23.decoder.layers.2.cross_attn.sampling_offsets.weight
model.23.decoder.layers.2.cross_attn.sampling_offsets.bias
model.23.decoder.layers.2.cross_attn.attention_weights.weight
model.23.decoder.layers.2.cross_attn.attention_weights.bias
model.23.decoder.layers.2.cross_attn.value_proj.weight
model.23.decoder.layers.2.cross_attn.value_proj.bias
model.23.decoder.layers.2.cross_attn.output_proj.weight
model.23.decoder.layers.2.cross_attn.output_proj.bias
model.23.decoder.layers.2.norm2.weight
model.23.decoder.layers.2.norm2.bias
model.23.decoder.layers.2.linear1.weight
model.23.decoder.layers.2.linear1.bias
model.23.decoder.layers.2.linear2.weight
model.23.decoder.layers.2.linear2.bias
model.23.decoder.layers.2.norm3.weight
model.23.decoder.layers.2.norm3.bias
model.23.decoder.layers.3.self_attn.in_proj_weight
model.23.decoder.layers.3.self_attn.in_proj_bias
model.23.decoder.layers.3.self_attn.out_proj.weight
model.23.decoder.layers.3.self_attn.out_proj.bias
model.23.decoder.layers.3.norm1.weight
model.23.decoder.layers.3.norm1.bias
model.23.decoder.layers.3.cross_attn.sampling_offsets.weight
model.23.decoder.layers.3.cross_attn.sampling_offsets.bias
model.23.decoder.layers.3.cross_attn.attention_weights.weight
model.23.decoder.layers.3.cross_attn.attention_weights.bias
model.23.decoder.layers.3.cross_attn.value_proj.weight
model.23.decoder.layers.3.cross_attn.value_proj.bias
model.23.decoder.layers.3.cross_attn.output_proj.weight
model.23.decoder.layers.3.cross_attn.output_proj.bias
model.23.decoder.layers.3.norm2.weight
model.23.decoder.layers.3.norm2.bias
model.23.decoder.layers.3.linear1.weight
model.23.decoder.layers.3.linear1.bias
model.23.decoder.layers.3.linear2.weight
model.23.decoder.layers.3.linear2.bias
model.23.decoder.layers.3.norm3.weight
model.23.decoder.layers.3.norm3.bias
model.23.decoder.layers.4.self_attn.in_proj_weight
model.23.decoder.layers.4.self_attn.in_proj_bias
model.23.decoder.layers.4.self_attn.out_proj.weight
model.23.decoder.layers.4.self_attn.out_proj.bias
model.23.decoder.layers.4.norm1.weight
model.23.decoder.layers.4.norm1.bias
model.23.decoder.layers.4.cross_attn.sampling_offsets.weight
model.23.decoder.layers.4.cross_attn.sampling_offsets.bias
model.23.decoder.layers.4.cross_attn.attention_weights.weight
model.23.decoder.layers.4.cross_attn.attention_weights.bias
model.23.decoder.layers.4.cross_attn.value_proj.weight
model.23.decoder.layers.4.cross_attn.value_proj.bias
model.23.decoder.layers.4.cross_attn.output_proj.weight
model.23.decoder.layers.4.cross_attn.output_proj.bias
model.23.decoder.layers.4.norm2.weight
model.23.decoder.layers.4.norm2.bias
model.23.decoder.layers.4.linear1.weight
model.23.decoder.layers.4.linear1.bias
model.23.decoder.layers.4.linear2.weight
model.23.decoder.layers.4.linear2.bias
model.23.decoder.layers.4.norm3.weight
model.23.decoder.layers.4.norm3.bias
model.23.decoder.layers.5.self_attn.in_proj_weight
model.23.decoder.layers.5.self_attn.in_proj_bias
model.23.decoder.layers.5.self_attn.out_proj.weight
model.23.decoder.layers.5.self_attn.out_proj.bias
model.23.decoder.layers.5.norm1.weight
model.23.decoder.layers.5.norm1.bias
model.23.decoder.layers.5.cross_attn.sampling_offsets.weight
model.23.decoder.layers.5.cross_attn.sampling_offsets.bias
model.23.decoder.layers.5.cross_attn.attention_weights.weight
model.23.decoder.layers.5.cross_attn.attention_weights.bias
model.23.decoder.layers.5.cross_attn.value_proj.weight
model.23.decoder.layers.5.cross_attn.value_proj.bias
model.23.decoder.layers.5.cross_attn.output_proj.weight
model.23.decoder.layers.5.cross_attn.output_proj.bias
model.23.decoder.layers.5.norm2.weight
model.23.decoder.layers.5.norm2.bias
model.23.decoder.layers.5.linear1.weight
model.23.decoder.layers.5.linear1.bias
model.23.decoder.layers.5.linear2.weight
model.23.decoder.layers.5.linear2.bias
model.23.decoder.layers.5.norm3.weight
model.23.decoder.layers.5.norm3.bias
model.23.denoising_class_embed.weight
model.23.query_pos_head.layers.0.weight
model.23.query_pos_head.layers.0.bias
model.23.query_pos_head.layers.1.weight
model.23.query_pos_head.layers.1.bias
model.23.enc_output.0.weight
model.23.enc_output.0.bias
model.23.enc_output.1.weight
model.23.enc_output.1.bias
model.23.enc_score_head.weight
model.23.enc_score_head.bias
model.23.enc_bbox_head.layers.0.weight
model.23.enc_bbox_head.layers.0.bias
model.23.enc_bbox_head.layers.1.weight
model.23.enc_bbox_head.layers.1.bias
model.23.enc_bbox_head.layers.2.weight
model.23.enc_bbox_head.layers.2.bias
model.23.dec_score_head.0.weight
model.23.dec_score_head.0.bias
model.23.dec_score_head.1.weight
model.23.dec_score_head.1.bias
model.23.dec_score_head.2.weight
model.23.dec_score_head.2.bias
model.23.dec_score_head.3.weight
model.23.dec_score_head.3.bias
model.23.dec_score_head.4.weight
model.23.dec_score_head.4.bias
model.23.dec_score_head.5.weight
model.23.dec_score_head.5.bias
model.23.dec_bbox_head.0.layers.0.weight
model.23.dec_bbox_head.0.layers.0.bias
model.23.dec_bbox_head.0.layers.1.weight
model.23.dec_bbox_head.0.layers.1.bias
model.23.dec_bbox_head.0.layers.2.weight
model.23.dec_bbox_head.0.layers.2.bias
model.23.dec_bbox_head.1.layers.0.weight
model.23.dec_bbox_head.1.layers.0.bias
model.23.dec_bbox_head.1.layers.1.weight
model.23.dec_bbox_head.1.layers.1.bias
model.23.dec_bbox_head.1.layers.2.weight
model.23.dec_bbox_head.1.layers.2.bias
model.23.dec_bbox_head.2.layers.0.weight
model.23.dec_bbox_head.2.layers.0.bias
model.23.dec_bbox_head.2.layers.1.weight
model.23.dec_bbox_head.2.layers.1.bias
model.23.dec_bbox_head.2.layers.2.weight
model.23.dec_bbox_head.2.layers.2.bias
model.23.dec_bbox_head.3.layers.0.weight
model.23.dec_bbox_head.3.layers.0.bias
model.23.dec_bbox_head.3.layers.1.weight
model.23.dec_bbox_head.3.layers.1.bias
model.23.dec_bbox_head.3.layers.2.weight
model.23.dec_bbox_head.3.layers.2.bias
model.23.dec_bbox_head.4.layers.0.weight
model.23.dec_bbox_head.4.layers.0.bias
model.23.dec_bbox_head.4.layers.1.weight
model.23.dec_bbox_head.4.layers.1.bias
model.23.dec_bbox_head.4.layers.2.weight
model.23.dec_bbox_head.4.layers.2.bias
model.23.dec_bbox_head.5.layers.0.weight
model.23.dec_bbox_head.5.layers.0.bias
model.23.dec_bbox_head.5.layers.1.weight
model.23.dec_bbox_head.5.layers.1.bias
model.23.dec_bbox_head.5.layers.2.weight
model.23.dec_bbox_head.5.layers.2.bias

"""
